version: '3.8'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ="America/Sao_Paulo"
      - PLEX_CLAIM=$TOKEN
    network_mode: host
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/transcode:/transcode
      - /mnt/nextcloud/sharedmedia:/data
